# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: SnapEnv App Template
site_description: SnapEnv App template.
site_author: 'Abner G Jacobsen'
docs_dir: docs/
repo_name: 'snapenv/snap-faststream-template'
repo_url: 'https://github.com/snapenv/snap-faststream-template'

plugins:
  - search
  - mike
  - awesome-pages
  - macros:
      modules:
        - mkdocs_macros_adr_summary
  - gen-files:
      scripts:
        - scripts/gen_pages.py  # or any other name or path
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            docstring_section_style: spacy

# Do not use the nav section in this file but reference to the .pages files
# in the docs/ directory and subdirectories (awesome-pages plugin)
# https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin
#nav:
#  - Home: index.md

theme:
  name: material
  custom_dir: mkdocs-overrides
  features:
    - navigation.expand
    - navigation.top
    - content.code.copy

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: teal
      toggle:
        icon: material/brightness-7
        name: Switch to auto mode

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/abnerjacobsen/
  version:
    provider: mike
    default: stable

markdown_extensions:
  - pymdownx.details
  - pymdownx.blocks.admonition
  - pymdownx.blocks.details
  - pymdownx.snippets
  - pymdownx.superfences
